import React from 'react';

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="mb-8">
    <h3 className="text-2xl font-bold text-gray-800 dark:text-gray-200 mb-4">{title}</h3>
    <div className="prose prose-lg dark:prose-invert max-w-none text-gray-600 dark:text-gray-400 space-y-4">
      {children}
    </div>
  </div>
);

export const TermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto bg-white dark:bg-gray-800 p-8 sm:p-12 rounded-xl shadow-lg">
      <div className="text-center mb-12">
        <h2 className="text-4xl font-extrabold text-gray-800 dark:text-gray-100 sm:text-5xl">
          Terms of Service
        </h2>
        <p className="mt-4 text-lg text-gray-500 dark:text-gray-400">
          Last Updated: {new Date().toLocaleDateString()}
        </p>
      </div>

      <Section title="1. Acceptance of Terms">
        <p>
          By accessing and using AI Landscaping Redesigner ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services. Any participation in this service will constitute acceptance of this agreement. If you do not agree to abide by the above, please do not use this service.
        </p>
      </Section>
      
      <Section title="2. Description of Service">
        <p>
          The Service is an AI-powered tool that allows users to upload images of their outdoor spaces and generate redesign concepts. The Service is provided "as is" and the accuracy, completeness, or usefulness of any generated content is not guaranteed. The designs are for inspirational purposes and should not be considered professional landscaping advice.
        </p>
      </Section>
      
      <Section title="3. User Conduct and Responsibilities">
        <p>
          You are solely responsible for the images and content you upload to the Service. You agree not to upload any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable. You are responsible for ensuring you have the necessary rights to any images you upload.
        </p>
      </Section>
      
      <Section title="4. Intellectual Property">
        <p>
          You retain all ownership rights to the original images you upload. By using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and display the content solely for the purpose of providing and improving the Service. The redesigned images generated by the Service can be used for personal and commercial purposes, subject to the limitations of your subscription plan.
        </p>
      </Section>

      <Section title="5. Limitation of Liability">
        <p>
          In no event shall AI Landscaping Redesigner, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
        </p>
      </Section>
    </div>
  );
};
